### ISSUE TITLE
9주차 과제 2번 질문드립니다.

### ISSUE THREAD

**Issue by yeongunkim** [CNUCOM/Comp1_CNU_2024#55]
public class Main {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int n = sc.nextInt();
        int [][] arr = new int[n][n];
        for(int i = 0; i<n; i++) {
            for (int j = 0; j < n; j++) {
                arr[i][j] = sc.nextInt();
            }
        }
        for (int x = 0; x<n; x++){
            System.out.println();
            for (int y = n-1; y>=0; y--){
                System.out.print(arr[y][x]+" ");
                }
            }
        }
    }
이렇게 코드를 작성하게 되었을 때 출력이 정상적으로 되지만 테스트케이스를 1개도 통과하지 못합니다. 어떠한 문제가 있을까요?

**Comment by Masterwhiece** [comment]
안녕하세요. TA 노유정입니다.  

90도 돌린 행렬을 출력하기 전에 줄바꿈이 출력되네요.

**Comment by yeongunkim** [comment]
답변 감사합니다
