### ISSUE TITLE
9주차 2번과제 질문합니다.

### ISSUE THREAD

**Issue by leesubeeeeen** [CNUCOM/Comp1_CNU_2024#56]
![스크린샷 2024-05-02 231921](https://github.com/CNUCOM/Comp1_CNU_2024/assets/162393332/5d6d3535-58b8-40c9-8792-acd1ea050b2e)
![스크린샷 2024-05-02 231938](https://github.com/CNUCOM/Comp1_CNU_2024/assets/162393332/c8ac1496-879e-4aa6-bc8a-2d085723783b)

이렇게 출력이 정상적으로 되는데 테스트케이스 통과를 못합니다.
어디가 잘못된걸까요

**Comment by Masterwhiece** [comment]
안녕하세요. TA 노유정입니다.  

여러 가지 포인트를 설명드릴 수 있을 것 같습니다.  
  
첫 번째, 입력입니다.  
문제 명세에 따르면, **첫 줄**에 배열의 크기 N이 입력됩니다.  
이후 **줄을 바꿔가며**, **N줄에 걸쳐** 각 행의 정보를 입력받고, **각 행은 공백으로 구분된 숫자**로 구성됩니다.  
  
그러므로 입력은 학생이 입력한 것과는 다른 형태로, 다음과 같을 것입니다.  
```
3
69 59 58
60 1 23
11 47 58
```

두 번째, 출력입니다.  
문제 명세에 따르면, **회전된 그리드만**을 출력합니다.  
학생의 코드를 실행한 결과로는, **원본 행렬**과 **줄바꿈**과 **회전된 행렬**이 차례로 출력되네요.  


참고로 코드는, 캡처본 말고 직접 업로드 부탁드립니다.  
일단 제가 언급해드린 부분들 생각해서 코드를 수정해서 다시 제출해보길 바랍니다. (아마 출력 문제겠죠.)
